### ISSUE TITLE
在window系统运行时遇到[生成图片失败]的问题

### ISSUE THREAD

**Issue by tt5753** [SummerSec/SPATool#1]
可以将方法签名中的空格改为短横(-)
ToCebBank-void-sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot

`2022.02.19 at 12:31:11 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).png]
2022.02.19 at 12:31:12 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot`

**Comment by SummerSec** [comment]
麻烦提供测试代码，如果是class文件，也麻烦提供一下。

**Comment by tt5753** [comment]
导入的是class文件, 日志见附件
















在 2022-02-19 12:53:38，"夏天" ***@***.***> 写道：

麻烦提供测试代码，如果是class文件，也麻烦提供一下。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
package com.yu.fierys.mail;

import org.apache.commons.compress.archivers.zip.ZipArchiveEntry;
import org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.simplejavamail.api.email.Email;
import org.simplejavamail.api.mailer.Mailer;
import org.simplejavamail.api.mailer.config.TransportStrategy;
import org.simplejavamail.email.EmailBuilder;
import org.simplejavamail.mailer.MailerBuilder;

import jakarta.mail.util.ByteArrayDataSource;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ToCebBank {

    private static int ZIP_SPLIT_SIZE = 7 * 1024 * 1024;

    public static void main(String[] args) throws Exception {

        String toMail = args[0];
        String zipFile = args[1];

        System.out.println(toMail);
        System.out.println(zipFile);

//        File zip = compress("f:/Game/batch/Notepads_1.4.5.0.zip");

        File batchZip = compress(zipFile);
        System.out.println(batchZip.getAbsolutePath());
        sendBatchMail(toMail, batchZip.getAbsolutePath());

//        ***@***.***", "F:/Game/batch/qifengle.mp3.z02");

//        ***@***.***", "F:/Game/batch");

    }

    public static void sendBatchMail(String toAddress, String path) throws IOException {
        File files = new File(path);
        File[] listFiles = files.listFiles();
        int total = listFiles.length;
        for (int i = 0; i < total; i++) {
            sendOneMail(toAddress, listFiles[i].getAbsolutePath(), "当前第 [" + (i + 1) + "] 个, 总数 [" + total + "]");
            System.out.println("Mail sent successfully --> " + listFiles[i].getAbsolutePath());
        }
    }

    public static void sendOneMail(String toAddress, String filePath, String notes) throws IOException {
        Email email = getMail(toAddress, filePath, notes);
        Mailer mailer = getMailer();
        mailer.sendMail(email);
        mailer.shutdownConnectionPool();
    }

    public static Email getMail(String toAddress, String filePath, String notes) throws IOException {
        File file = new File(filePath);
        byte[] byteArray = IOUtils.toByteArray(new FileInputStream(file));

        Email email = EmailBuilder.startingBlank()
                .***@***.***")
                .to(toAddress)
                .withSubject(file.getName())
                .withPlainText("来自脚本: 自动分割压缩,自动发送附件. --> " + notes)
                .withAttachment(file.getName(), new ByteArrayDataSource(byteArray, "application/octet-stream"))
                .withHeader("X-Priority", 5)
                .buildEmail();
        return email;
    }

    public static Mailer getMailer() {
        Mailer mailer = MailerBuilder
                .withSMTPServer("smtp.163.com", 25, ***@***.***", "EJQJCLKKJVXBCMDA")
                .withTransportStrategy(TransportStrategy.SMTP_TLS)
                .withSessionTimeout(10 * 1000)
                .withProperty("mail.smtp.sendpartial", true)
                .withDebugLogging(false)
//                .async()
                .buildMailer();
        return mailer;
    }

    public static File compress(String sourceFile) throws IOException {

        File file = new File(sourceFile);
        File zipFile = new File(file.getParent() + "/"
                + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss")));
        FileUtils.forceMkdir(zipFile);
        File archive = new File(zipFile, file.getName() + ".zip");

        try (ZipArchiveOutputStream outputStream = new ZipArchiveOutputStream(archive, ZIP_SPLIT_SIZE)) {
            ZipArchiveEntry entry = new ZipArchiveEntry(sourceFile);
            outputStream.putArchiveEntry(entry);
            outputStream.write(IOUtils.toByteArray(new FileInputStream(new File(sourceFile))));
            outputStream.closeArchiveEntry();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return zipFile;
    }
}

2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.main 33 main - No arguments provided
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.main 34 main - Starting application with default arguments
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 227 init - 初始化成功
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 228 init - CFG文件存储路径为：E:\Users\admin\Downloads\datas\cfg\500216241340700
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 229 init - AST文件存储路径为：E:\Users\admin\Downloads\datas\ast\500216241356800
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 230 init - 结果文件存储路径为：E:\Users\admin\Downloads\datas\result\cfg\500216241351000
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 231 init - soot输出文件存储路径为：datas\sootOutput\500216241354900
2022.02.19 at 12:27:31 CST INFO  com.sumsec.ui.mainController 232 init - ASTResultTemp：E:\Users\admin\Downloads\datas\result\ast\500216241358500
2022.02.19 at 12:27:32 CST INFO  com.sumsec.ui.main 53 start - Application started
2022.02.19 at 12:30:34 CST INFO  com.sumsec.ui.mainController 82 CFGFile - 选择class文件
2022.02.19 at 12:30:34 CST INFO  com.sumsec.util.SelectFile 27 SelectFile - 选择文件
2022.02.19 at 12:30:40 CST INFO  com.sumsec.util.SelectFile 35 SelectFile - 选择了文件：E:\devops\consul\tools\target\classes\com\yu\fierys\mail\ToCebBank.class
2022.02.19 at 12:30:40 CST INFO  com.sumsec.ui.mainController 87 CFGFile - 选择的文件名为：ToCebBank.class
2022.02.19 at 12:30:40 CST INFO  com.sumsec.ui.mainController 88 CFGFile - 选择的文件路径为：E:\devops\consul\tools\target\classes\com\yu\fierys\mail\ToCebBank.class
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.SelectC 22 selectFile - select file: E:\devops\consul\tools\target\classes\com\yu\fierys\mail\ToCebBank.class
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.SelectC 23 selectFile - 复制Class文件到：E:\Users\admin\Downloads\datas\cfg\500216241340700
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.SelectC 27 selectFile - 复制成功 E:\Users\admin\Downloads\datas\cfg\500216241340700\ToCebBank.class
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.Generate 53 DotG - 准备环境 prepare
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.Prepare 20 Envprepare - 检测环境
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.Prepare 25 Envprepare - CFG环境设置完成
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.uitls.Prepare 26 Envprepare - CFG Home: E:\Users\admin\Downloads\datas\cfg\500216241340700
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.Generate 70 DotG - arg: ToCebBank --graph=BriefUnitGraph -force-overwrite -d datas\sootOutput\500216241354900
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.Generate 71 DotG - 开始生成cfg图
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.Generate 72 DotG - 生成的文件名为：ToCebBank
2022.02.19 at 12:31:05 CST INFO  com.sumsec.core.cfg.Generate 73 DotG - 生成的图类型为：BriefUnitGraph
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.Generate 75 DotG - cfg图生成完成
2022.02.19 at 12:31:06 CST INFO  com.sumsec.ui.mainController 125 CFGG - 生成cfg的dot文件成功
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.ImageUtil 66 Dot2Image - Dot2Image
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 24 findDotCFG - 开始寻找dot文件
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank java.io.File compress(java.lang.String).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.email.Email getMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.mailer.Mailer getMailer().dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void main(java.lang.String[]).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendBatchMail(java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.FindDot 30 findDotCFG - 找到dot文件：E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 30 isWindowsOS - 当前操作系统为：Windows 10
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 42 RunCmd - 6
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank java.io.File compress(java.lang.String).dot
2022.02.19 at 12:31:06 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank java.io.File compress(java.lang.String).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank java.io.File compress(java.lang.String).png]
2022.02.19 at 12:31:07 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank java.io.File compress(java.lang.String).dot
2022.02.19 at 12:31:07 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null
2022.02.19 at 12:31:07 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.email.Email getMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:07 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.email.Email getMail(java.lang.String,java.lang.String,java.lang.String).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank org.simplejavamail.api.email.Email getMail(java.lang.String,java.lang.String,java.lang.String).png]
2022.02.19 at 12:31:08 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.email.Email getMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:08 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null
2022.02.19 at 12:31:08 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.mailer.Mailer getMailer().dot
2022.02.19 at 12:31:08 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.mailer.Mailer getMailer().dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank org.simplejavamail.api.mailer.Mailer getMailer().png]
2022.02.19 at 12:31:09 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank org.simplejavamail.api.mailer.Mailer getMailer().dot
2022.02.19 at 12:31:09 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null
2022.02.19 at 12:31:09 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void main(java.lang.String[]).dot
2022.02.19 at 12:31:09 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void main(java.lang.String[]).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank void main(java.lang.String[]).png]
2022.02.19 at 12:31:10 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void main(java.lang.String[]).dot
2022.02.19 at 12:31:10 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null
2022.02.19 at 12:31:10 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendBatchMail(java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:10 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendBatchMail(java.lang.String,java.lang.String).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank void sendBatchMail(java.lang.String,java.lang.String).png]
2022.02.19 at 12:31:11 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendBatchMail(java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:11 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null
2022.02.19 at 12:31:11 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 54 RunCmd - 开始生成图片 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:11 CST INFO  com.sumsec.core.cfg.uitls.OSUtil 55 RunCmd - 正在执行命令 [cmd.exe, /c, dot, -Tpng, E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot, -o, E:\Users\admin\Downloads\datas\result\cfg\500216241351000\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).png]
2022.02.19 at 12:31:12 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 72 RunCmd - 生成图片失败 E:\Users\admin\Downloads\datas\sootOutput\500216241354900\ToCebBank void sendOneMail(java.lang.String,java.lang.String,java.lang.String).dot
2022.02.19 at 12:31:12 CST ERROR com.sumsec.core.cfg.uitls.OSUtil 77 RunCmd - null

**Comment by SummerSec** [comment]
> 
邮件回复，我这边是看不到附件的。麻烦在GitHub上传一下。谢谢

**Comment by SummerSec** [comment]
或者提供一个下载链接也行。

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/154788500-9e5ad5c6-c92e-42c0-b1ea-029e2e4d452d.png)

![image](https://user-images.githubusercontent.com/47944478/154788504-66f9f3bb-c0e5-45d4-9538-8a1d619b09ed.png)
我这测试通过了呀，`第一步必须下载安装[Graphviz](https://graphviz.org/download/)，并配置环境变量。`这步做了吗？

**Comment by SummerSec** [comment]
请在命令执行环境中下执行，`dot -h`查看是否存在环境。

**Comment by tt5753** [comment]
拉了源码, 调试了下, 不是dot命令的问题, 是在我的机器里面 
执行Runtime.getRuntime().exec(cmd).getInputStream(); 后获得的这个 steam的 大小是0, 见图, 我改了下, 就正常了
![image](https://user-images.githubusercontent.com/4957334/154790786-ade1354c-6789-49b6-86ef-941a3632be27.png)
![image](https://user-images.githubusercontent.com/4957334/154790837-e2c6c48f-0b68-4236-acee-904689867a23.png)
![image](https://user-images.githubusercontent.com/4957334/154790839-6da53a4d-1cfb-4d7d-b040-8d026ac67002.png)

**Comment by SummerSec** [comment]
> 拉了源码, 调试了下, 不是dot命令的问题, 是在我的机器里面 执行Runtime.getRuntime().exec(cmd).getInputStream(); 后获得的这个 steam的 大小是0, 见图, 我改了下, 就正常了 ![image](https://user-images.githubusercontent.com/4957334/154790786-ade1354c-6789-49b6-86ef-941a3632be27.png) ![image](https://user-images.githubusercontent.com/4957334/154790837-e2c6c48f-0b68-4236-acee-904689867a23.png) ![image](https://user-images.githubusercontent.com/4957334/154790839-6da53a4d-1cfb-4d7d-b040-8d026ac67002.png)

感谢！我的机器上不是0，后续改变一下逻辑。执行命令之后判断是否图片是否存在，如果没有在报错。

**Comment by tt5753** [comment]
还发现个小问题 com.sumsec.core.ast.Parser  这个类的java文件 parser.java  p是小写的, 好像会编译错误

**Comment by SummerSec** [comment]
> 还发现个小问题 com.sumsec.core.ast.Parser 这个类的java文件 parser.java p是小写的, 好像会编译错误

是的，一开始小写，后面改成大写了。但git是忽略文件名大小写。我一直忽视了这个问题，下一个版本也会修复的。

**Comment by SummerSec** [comment]
这个问题在正式版本被修复了，采用先判断图片是否存在。
