### ISSUE TITLE
bug report: process cmd error on Linux

### ISSUE THREAD

**Issue by LycsHub** [SummerSec/SPATool#2]
## Env
- OS:  Pop!_OS 20.04 LTS(base on Ubuntu 20.04)

 ## Log

[![bQ8YJH.md.png](https://s4.ax1x.com/2022/03/01/bQ8YJH.md.png)](https://imgtu.com/i/bQ8YJH)

## Reason
https://github.com/SummerSec/SPATool/blob/2823aef4adf0f8c3a9a5dfebb239cc760e6ecea1/src/main/java/com/sumsec/core/ast/util/DotHandler.java#L44

Like windows if branch , replace "+" to "," may fix the bug.

**Comment by SummerSec** [comment]
thank you，I fixed this problem in the official version.

**Comment by LycsHub** [comment]
hey bro, thx your quick fix,but its still has some problems.
At the same place , I edit some source code to compatible with Linux and it work good for me.
```java
       if (isWindowsOS) {
                //windows下的命令
                cmd = new String[]{"cmd.exe", "/c", "dot", "-Tpng", dotPath[i], "-o", imgPath};
            } else {
                //linux下的命令
//              imgPath =  ConstatField.ASTResultTemp  + ConstatField.separator + dotPath[i].substring(dotPath[i].lastIndexOf("\\") + 1, dotPath[i].lastIndexOf(".")) + ".png";

                // fixme:for example path ,change yourself, the imgPath in unix will be like:
                // $home/proj/tools/datas/result/ast/1225819235468336//$home/proj/tools/datas/ast/1225819235466361/1225833393958640.png
                // has tow slash in imgPath
                imgPath = ConstatField.ASTResultTemp + ConstatField.separator + dotPath[i].lastIndexOf(".") + ".png";
                //fixme: use `/usr/bash -c` may has problem in some shell like  zsh
                cmd = new String[]{"dot", "-Tpng" , dotPath[i] , "-o", imgPath};
            }
            try {
                logger.info("开始生成图片 " + dotPath[i]);
                logger.info("正在执行命令 "+ Arrays.toString(cmd));
                sleep(1000);
                String charsetName = isWindowsOS ? "GBK" : "UTF-8";
                Runtime.getRuntime().exec(cmd);
//                byte[] bytes = new Scanner(Runtime.getRuntime().exec(cmd).getInputStream(), charsetName).useDelimiter("\\A").next().getBytes(charsetName);

                byte[] bytes = null;
                Scanner runCmd = new Scanner(Runtime.getRuntime().exec(cmd).getInputStream(), charsetName).useDelimiter("\\A");
                //fixme: on linux : detect hasNext otherwise will throw a NoSuchElementException
                if (runCmd.hasNext())
                    bytes = runCmd.next().getBytes(charsetName);
//...
```

**by the way the cfg module may same problems**

**Comment by SummerSec** [comment]
Thanks for the suggestion, this looks great, can you submit a pull request for this project?

> hey bro, thx your quick fix,but its still has some problems. At the same place , I edit some source code to compatible with Linux and it work good for me.
> 
> ```java
>        if (isWindowsOS) {
>                 //windows下的命令
>                 cmd = new String[]{"cmd.exe", "/c", "dot", "-Tpng", dotPath[i], "-o", imgPath};
>             } else {
>                 //linux下的命令
> //              imgPath =  ConstatField.ASTResultTemp  + ConstatField.separator + dotPath[i].substring(dotPath[i].lastIndexOf("\\") + 1, dotPath[i].lastIndexOf(".")) + ".png";
> 
>                 // fixme:for example path ,change yourself, the imgPath in unix will be like:
>                 // $home/proj/tools/datas/result/ast/1225819235468336//$home/proj/tools/datas/ast/1225819235466361/1225833393958640.png
>                 // has tow slash in imgPath
>                 imgPath = ConstatField.ASTResultTemp + ConstatField.separator + dotPath[i].lastIndexOf(".") + ".png";
>                 //fixme: use `/usr/bash -c` may has problem in some shell like  zsh
>                 cmd = new String[]{"dot", "-Tpng" , dotPath[i] , "-o", imgPath};
>             }
>             try {
>                 logger.info("开始生成图片 " + dotPath[i]);
>                 logger.info("正在执行命令 "+ Arrays.toString(cmd));
>                 sleep(1000);
>                 String charsetName = isWindowsOS ? "GBK" : "UTF-8";
>                 Runtime.getRuntime().exec(cmd);
> //                byte[] bytes = new Scanner(Runtime.getRuntime().exec(cmd).getInputStream(), charsetName).useDelimiter("\\A").next().getBytes(charsetName);
> 
>                 byte[] bytes = null;
>                 Scanner runCmd = new Scanner(Runtime.getRuntime().exec(cmd).getInputStream(), charsetName).useDelimiter("\\A");
>                 //fixme: on linux : detect hasNext otherwise will throw a NoSuchElementException
>                 if (runCmd.hasNext())
>                     bytes = runCmd.next().getBytes(charsetName);
> //...
> ```
> 
> **by the way the cfg module may same problems**

**Comment by SummerSec** [comment]
Because my OS is Windows, I can't do the test well on Linux environment. If it is convenient for you, could you please submit a pr?

**Comment by LycsHub** [comment]
ok , I'll submit a pr later :)
